## IRIS

In [4]:
from IPython.display import HTML
HTML('<iframe src="http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data" width=300 height=200></iframe>')

In [7]:
#import load_iris function from dataset module
from sklearn.datasets import load_iris

In [10]:
#save "bunch" object containing iris dataset and its attributes
iris=load_iris()
type(iris)

sklearn.datasets.base.Bunch

In [16]:
#print the iris data
print iris.data

In [18]:
# Each row = obseervation
# Each column = feature


In [20]:
#print the name of iris feature
print iris.feature_names

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [21]:
print iris.target_names

['setosa' 'versicolor' 'virginica']


In [23]:
print iris.target

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [24]:
## target =response,label,depend var

## classification => categorical 
## regression => continues

# Requirement for work with data

In [27]:
#check the type of feature and response
print type(iris.data)
print type(iris.target)

<type 'numpy.ndarray'>
<type 'numpy.ndarray'>


In [29]:
#check the shape of the feature
print iris.data.shape

(150L, 4L)


In [31]:
print iris.target.shape

(150L,)


In [47]:
#numpy -> high DM array

#store featue matrix in x
x=iris.data
#store response vector in y
y=iris.target

<hr>
session 3
## KNN (part training movie)


1. pick value for k

2. search for k observation in training data tha is "nearest" to the measuremetn of the unknown iris
calculate numeric distance unknown+each known iris => select smallest distance

3. use the most popular response value from k nearest neighbour

In [49]:
#import load_iris function form dataset module

from sklearn.datasets import load_iris

iris=load_iris()

x=iris.data
y=iris.target

print x.shape
print y.shape


(150L, 4L)
(150L,)


In [61]:
#import class to use
from sklearn.neighbors import KNeighborsClassifier

#instantiate the estimator
knn = KNeighborsClassifier(n_neighbors=1)
#n_neighbor is tuning parameter
#another parameter is default
#print knn

##fit model to data
knn.fit(x,y)


##predict the response for observation
knn.predict([3, 5, 4, 2]) #return numpy array


#if we want to predict 2 ex. in one step
x_new=[[3,5,4,2],[5,4,3,2]]
knn.predict(x_new)

C:\Users\Yasin\Anaconda2\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([2, 1])

## using diffrent k

In [65]:
#instantiate the estimator
knn = KNeighborsClassifier(n_neighbors=5)
#n_neighbor is tuning parameter
#another parameter is default
#print knn

##fit model to data
knn.fit(x,y)


#if we want to predict 2 ex. in one step
x_new=[[3,5,4,2],[5,4,3,2]]
knn.predict(x_new)

array([1, 1])


## using diffrent classification model

logistic regression

In [69]:
#import the class
from sklearn.linear_model import LogisticRegression

#instantiate the model (using the default parameter)
logreg = LogisticRegression()

#fit the model
logreg.fit(x,y)

#predict
logreg.predict(x_new)

array([2, 0])